### ISSUE TITLE
是否支持ios？

### ISSUE THREAD

**Issue by cjpxyz** [chiuan/TTConsole#9]
在ios平台打包时遇到错误。
Failed running /Applications/Unity/Unity.app/Contents/Tools/UnusedByteCodeStripper2/UnusedBytecodeStripper2.exe --api NET_2_0 -out "/Users/eahorse/program/horserace/HorseRace/Temp/StagingArea/Data/Managed/tempStrip" -l none -c link -b False -x "/Applications/Unity/PlaybackEngines/iOSSupport/Whitelists/Core.xml" -f "/Applications/Unity/Unity.app/Contents/il2cpp/LinkerDescriptors" -x "/Users/eahorse/program/horserace/HorseRace/Temp/StagingArea/Data/Managed/../platform_native_link.xml" -x "/Users/eahorse/program/horserace/HorseRace/Temp/StagingArea/Data/methods_pointedto_by_uievents.xml" -x "/Users/eahorse/program/horserace/HorseRace/Temp/StagingArea/Data/preserved_derived_types.xml" -d "/Users/eahorse/program/horserace/HorseRace/Temp/StagingArea/Data/Managed" -a  "/Users/eahorse/program/horserace/HorseRace/Temp/StagingArea/Data/Managed/Assembly-CSharp-firstpass.dll" -a  "/Users/eahorse/program/horserace/HorseRace/Temp/StagingArea/Data/Managed/Assembly-CSharp.dll" -a  "/Users/eahorse/program/horserace/HorseRace/Temp/StagingArea/Data/Managed/Assembly-U
nityScript-firstpass.dll" -a  "/Users/eahorse/program/horserace/HorseRace/Temp/StagingArea/Data/Managed/Assembly-UnityScript.dll" -a  "/Users/eahorse/program/horserace/HorseRace/Temp/StagingArea/Data/Managed/UnityEngine.UI.dll"

stdout:
SweepReport:
System.MonoType => Mono.Cecil.TypeDefinitionMono.Cecil.TypeDefinitionMono.Cecil.TypeDefinitionMono.Cecil.TypeDefinitionMono.Cecil.TypeDefinition
Mono.Cecil.MethodDefinition => System.Void .ctor()System.Void .ctor(System.String)System.String get_Comment()System.Void .ctor()System.Void Source1AndSource2(System.Object,System.Object)
Mono.Cecil.FieldDefinition => System.String commentSystem.Func`3<System.Int32,System.Int32,System.Int32> <>f__am$cache0System.Func`3<System.Int64,System.Int64,System.Int64> <>f__am$cache1System.Func`3<System.Double,System.Double,System.Double> <>f__am$cache2System.Func`3<System.Single,System.Single,System.Single> <>f__am$cache3
Fatal error in Mono CIL Linker
Mono.Cecil.ResolutionException: Failed to resolve UnityEngine.Profiling.Profiler
  at UnusedBytecodeStripper2.AddUnresolvedStubsStep.Process () <0x103ae8860 + 0x002fd> in <filename unknown>:0 
  at Mono.Linker.Steps.BaseStep.Process (Mono.Linker.LinkContext context) <0x102e39710 + 0x0006b> in <filename unknown>:0 
  at Mono.Linker.Pipeline.Process (Mono.Linker.LinkContext context) <0x102e387d0 + 0x000e6> in <filename unknown>:0 
  at Mono.Linker.Driver.Run (IEqualityComparer`1 typeComparer, IEqualityComparer`1 methodComparer) <0x1006a0430 + 0x00be7> in <filename unknown>:0 
  at Mono.Linker.Driver.RunDriverWithErrorHandling (Mono.Linker.Driver driver, IEqualityComparer`1 typeComparer, IEqualityComparer`1 methodComparer) <0x1006a03e0 + 0x00026> in <filename unknown>:0 
  at Mono.Linker.Driver.RunDriver (Mono.Linker.Driver driver, IEqualityComparer`1 typeComparer, IEqualityComparer`1 methodComparer) <0x1006a02f0 + 0x0003b> in <filename unknown>:0 
stderr:

UnityEngine.Debug:LogError(Object)
UnityEditorInternal.Runner:RunManagedProgram(String, String, String, CompilerOutputParserBase, Action`1) (at /Users/builduser/buildslave/unity/build/Editor/Mono/BuildPipeline/BuildUtils.cs:96)
UnityEditorInternal.AssemblyStripper:RunAssemblyLinker(IEnumerable`1, String&, String&, String, String) (at /Users/builduser/buildslave/unity/build/Editor/Mono/BuildPipeline/AssemblyStripper.cs:104)
UnityEditorInternal.AssemblyStripper:StripAssembliesTo(String[], String[], String, String, String&, String&, String, IIl2CppPlatformProvider, IEnumerable`1, Boolean) (at /Users/builduser/buildslave/unity/build/Editor/Mono/BuildPipeline/AssemblyStripper.cs:97)
UnityEditorInternal.AssemblyStripper:RunAssemblyStripper(String, IEnumerable, String, String[], String[], String, IIl2CppPlatformProvider, RuntimeClassRegistry, Boolean) (at /Users/builduser/buildslave/unity/build/Editor/Mono/BuildPipeline/AssemblyStripper.cs:196)
UnityEditorInternal.AssemblyStripper:StripAssemblies(String, IIl2CppPlatformProvider, RuntimeClassRegistry, Boolean) (at /Users/builduser/buildslave/unity/build/Editor/Mono/BuildPipeline/AssemblyStripper.cs:128)
UnityEditorInternal.IL2CPPBuilder:Run() (at /Users/builduser/buildslave/unity/build/Editor/Mono/BuildPipeline/Il2Cpp/IL2CPPUtils.cs:118)
UnityEditorInternal.IL2CPPUtils:RunIl2Cpp(String, String, IIl2CppPlatformProvider, Action`1, RuntimeClassRegistry, Boolean) (at /Users/builduser/buildslave/unity/build/Editor/Mono/BuildPipeline/Il2Cpp/IL2CPPUtils.cs:32)
UnityEditor.HostView:OnGUI()
Exception: /Applications/Unity/Unity.app/Contents/Tools/UnusedByteCodeStripper2/UnusedBytecodeStripper2.exe did not run properly!
UnityEditorInternal.Runner.RunManagedProgram (System.String exe, System.String args, System.String workingDirectory, UnityEditor.Scripting.Compilers.CompilerOutputParserBase parser, System.Action`1 setupStartInfo) (at /Users/builduser/buildslave/unity/build/Editor/Mono/BuildPipeline/BuildUtils.cs:98)
UnityEditorInternal.AssemblyStripper.RunAssemblyLinker (IEnumerable`1 args, System.String& out, System.String& err, System.String linkerPath, System.String workingDirectory) (at /Users/builduser/buildslave/unity/build/Editor/Mono/BuildPipeline/AssemblyStripper.cs:104)
UnityEditorInternal.AssemblyStripper.StripAssembliesTo (System.String[] assemblies, System.String[] searchDirs, System.String outputFolder, System.String workingDirectory, System.String& output, System.String& error, System.String linkerPath, IIl2CppPlatformProvider platformProvider, IEnumerable`1 additionalBlacklist, Boolean developmentBuild) (at /Users/builduser/buildslave/unity/build/Editor/Mono/BuildPipeline/AssemblyStripper.cs:97)
UnityEditorInternal.AssemblyStripper.RunAssemblyStripper (System.String stagingAreaData, IEnumerable assemblies, System.String managedAssemblyFolderPath, System.String[] assembliesToStrip, System.String[] searchDirs, System.String monoLinkerPath, IIl2CppPlatformProvider platformProvider, UnityEditor.RuntimeClassRegistry rcr, Boolean developmentBuild) (at /Users/builduser/buildslave/unity/build/Editor/Mono/BuildPipeline/AssemblyStripper.cs:196)
UnityEditorInternal.AssemblyStripper.StripAssemblies (System.String stagingAreaData, IIl2CppPlatformProvider platformProvider, UnityEditor.RuntimeClassRegistry rcr, Boolean developmentBuild) (at /Users/builduser/buildslave/unity/build/Editor/Mono/BuildPipeline/AssemblyStripper.cs:128)
UnityEditorInternal.IL2CPPBuilder.Run () (at /Users/builduser/buildslave/unity/build/Editor/Mono/BuildPipeline/Il2Cpp/IL2CPPUtils.cs:118)
UnityEditorInternal.IL2CPPUtils.RunIl2Cpp (System.String tempFolder, System.String stagingAreaData, IIl2CppPlatformProvider platformProvider, System.Action`1 modifyOutputBeforeCompile, UnityEditor.RuntimeClassRegistry runtimeClassRegistry, Boolean developmentBuild) (at /Users/builduser/buildslave/unity/build/Editor/Mono/BuildPipeline/Il2Cpp/IL2CPPUtils.cs:32)
UnityEditor.iOS.PostProcessiPhonePlayer.CrossCompileManagedDlls (BuildSettings bs, UnityEditor.iOS.ProjectPaths paths, UnityEditor.AssemblyReferenceChecker checker, UnityEditor.RuntimeClassRegistry usedClassRegistry) (at /Users/builduser/buildslave/unity/build/PlatformDependent/iPhonePlayer/Extensions/Common/BuildPostProcessor.cs:664)
UnityEditor.iOS.PostProcessiPhonePlayer.PostProcess (BuildSettings bs, UnityEditor.iOS.ProjectPaths paths, UnityEditor.RuntimeClassRegistry usedClassRegistry) (at /Users/builduser/buildslave/unity/build/PlatformDependent/iPhonePlayer/Extensions/Common/BuildPostProcessor.cs:507)
UnityEditor.iOS.PostProcessiPhonePlayer.PostProcess (PostProcessorSettings postProcessorSettings, BuildPostProcessArgs args) (at /Users/builduser/buildslave/unity/build/PlatformDependent/iPhonePlayer/Extensions/Common/BuildPostProcessor.cs:478)
UnityEditor.iOS.iOSBuildPostprocessor.PostProcess (BuildPostProcessArgs args) (at /Users/builduser/buildslave/unity/build/PlatformDependent/iPhonePlayer/Extensions/Common/ExtensionModule.cs:34)
UnityEditor.PostprocessBuildPlayer.Postprocess (BuildTarget target, System.String installPath, System.String companyName, System.String productName, Int32 width, Int32 height, System.String downloadWebplayerUrl, System.String manualDownloadWebplayerUrl, BuildOptions options, UnityEditor.RuntimeClassRegistry usedClassRegistry, UnityEditor.BuildReporting.BuildReport report) (at /Users/builduser/buildslave/unity/build/Editor/Mono/BuildPipeline/PostprocessBuildPlayer.cs:186)
UnityEditor.HostView:OnGUI()Failed running /Applications/Unity/Unity.app/Contents/Tools/UnusedByteCodeStripper2/UnusedBytecodeStripper2.exe --api NET_2_0 -out "/Users/eahorse/program/horserace/HorseRace/Temp/StagingArea/Data/Managed/tempStrip" -l none -c link -b False -x "/Applications/Unity/PlaybackEngines/iOSSupport/Whitelists/Core.xml" -f "/Applications/Unity/Unity.app/Contents/il2cpp/LinkerDescriptors" -x "/Users/eahorse/program/horserace/HorseRace/Temp/StagingArea/Data/Managed/../platform_native_link.xml" -x "/Users/eahorse/program/horserace/HorseRace/Temp/StagingArea/Data/methods_pointedto_by_uievents.xml" -x "/Users/eahorse/program/horserace/HorseRace/Temp/StagingArea/Data/preserved_derived_types.xml" -d "/Users/eahorse/program/horserace/HorseRace/Temp/StagingArea/Data/Managed" -a  "/Users/eahorse/program/horserace/HorseRace/Temp/StagingArea/Data/Managed/Assembly-CSharp-firstpass.dll" -a  "/Users/eahorse/program/horserace/HorseRace/Temp/StagingArea/Data/Managed/Assembly-CSharp.dll" -a  "/Users/eahorse/program/horserace/HorseRace/Temp/StagingArea/Data/Managed/Assembly-UnityScript-firstpass.dll" -a  "/Users/eahorse/program/horserace/HorseRace/Temp/StagingArea/Data/Managed/Assembly-UnityScript.dll" -a  "/Users/eahorse/program/horserace/HorseRace/Temp/StagingArea/Data/Managed/UnityEngine.UI.dll"

stdout:
SweepReport:
System.MonoType => Mono.Cecil.TypeDefinitionMono.Cecil.TypeDefinitionMono.Cecil.TypeDefinitionMono.Cecil.TypeDefinitionMono.Cecil.TypeDefinition
Mono.Cecil.MethodDefinition => System.Void .ctor()System.Void .ctor(System.String)System.String get_Comment()System.Void .ctor()System.Void Source1AndSource2(System.Object,System.Object)
Mono.Cecil.FieldDefinition => System.String commentSystem.Func`3<System.Int32,System.Int32,System.Int32> <>f__am$cache0System.Func`3<System.Int64,System.Int64,System.Int64> <>f__am$cache1System.Func`3<System.Double,System.Double,System.Double> <>f__am$cache2System.Func`3<System.Single,System.Single,System.Single> <>f__am$cache3
Fatal error in Mono CIL Linker
Mono.Cecil.ResolutionException: Failed to resolve UnityEngine.Profiling.Profiler
  at UnusedBytecodeStripper2.AddUnresolvedStubsStep.Process () <0x1096e2860 + 0x002fd> in <filename unknown>:0 
  at Mono.Linker.Steps.BaseStep.Process (Mono.Linker.LinkContext context) <0x108a87710 + 0x0006b> in <filename unknown>:0 
  at Mono.Linker.Pipeline.Process (Mono.Linker.LinkContext context) <0x108a867d0 + 0x000e6> in <filename unknown>:0 
  at Mono.Linker.Driver.Run (IEqualityComparer`1 typeComparer, IEqualityComparer`1 methodComparer) <0x1062fb430 + 0x00be7> in <filename unknown>:0 
  at Mono.Linker.Driver.RunDriverWithErrorHandling (Mono.Linker.Driver driver, IEqualityComparer`1 typeComparer, IEqualityComparer`1 methodComparer) <0x1062fb3e0 + 0x00026> in <filename unknown>:0 
  at Mono.Linker.Driver.RunDriver (Mono.Linker.Driver driver, IEqualityComparer`1 typeComparer, IEqualityComparer`1 methodComparer) <0x1062fb2f0 + 0x0003b> in <filename unknown>:0 
stderr:

UnityEngine.Debug:LogError(Object)
UnityEditorInternal.Runner:RunManagedProgram(String, String, String, CompilerOutputParserBase, Action`1) (at /Users/builduser/buildslave/unity/build/Editor/Mono/BuildPipeline/BuildUtils.cs:96)
UnityEditorInternal.AssemblyStripper:RunAssemblyLinker(IEnumerable`1, String&, String&, String, String) (at /Users/builduser/buildslave/unity/build/Editor/Mono/BuildPipeline/AssemblyStripper.cs:104)
UnityEditorInternal.AssemblyStripper:StripAssembliesTo(String[], String[], String, String, String&, String&, String, IIl2CppPlatformProvider, IEnumerable`1, Boolean) (at /Users/builduser/buildslave/unity/build/Editor/Mono/BuildPipeline/AssemblyStripper.cs:97)
UnityEditorInternal.AssemblyStripper:RunAssemblyStripper(String, IEnumerable, String, String[], String[], String, IIl2CppPlatformProvider, RuntimeClassRegistry, Boolean) (at /Users/builduser/buildslave/unity/build/Editor/Mono/BuildPipeline/AssemblyStripper.cs:196)
UnityEditorInternal.AssemblyStripper:StripAssemblies(String, IIl2CppPlatformProvider, RuntimeClassRegistry, Boolean) (at /Users/builduser/buildslave/unity/build/Editor/Mono/BuildPipeline/AssemblyStripper.cs:128)
UnityEditorInternal.IL2CPPBuilder:Run() (at /Users/builduser/buildslave/unity/build/Editor/Mono/BuildPipeline/Il2Cpp/IL2CPPUtils.cs:118)
UnityEditorInternal.IL2CPPUtils:RunIl2Cpp(String, String, IIl2CppPlatformProvider, Action`1, RuntimeClassRegistry, Boolean) (at /Users/builduser/buildslave/unity/build/Editor/Mono/BuildPipeline/Il2Cpp/IL2CPPUtils.cs:32)
UnityEditor.HostView:OnGUI()

**Comment by chiuan** [comment]
支持的哈. 你这是你项目因为开了StripBytecode级别不对,或者排除下某些类导致的.
